language: r
sudo: false
cache: packages
apt_packages:
 - libudunits2-dev
 - libpoppler-cpp-dev
 - libgdal-dev
 - libgeos-dev
 - libproj-dev
git:
  depth: false
script:
 - Rscript -e 'source("R/dat_proc.R")'
 - Rscript -e "library(testthat); testthat::test_dir('tests/testthat', reporter = c('progress', 'fail'))"
 - git config --global user.name "fawda123"
 - git config --global user.email "mbafs2012@gmail.com"
 - git pull https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
 - git add -A
 - git commit -a -m "Updating desoto data build via travis-ci.org [ci skip]"
 - git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
notifications:
  email:
    recipients:
    - mbafs2012@gmail.com
    on_success: change
    on_failure: change
env:
  global:
  - TRAVIS_REPO_SLUG=tbep-tech/desoto-buoy
  - TRAVIS_BRANCH=master
  - CRAN: http://cran.rstudio.com
  - secure: 1DMYmIZixqaJBteg7CgZ/kPi6YLJL6oUhfIvE5IFd7jiRq9cmlSrTdXwqyrRSzp+gvd3jb40DFIt9nQWYFSlCOQo2urnpc6m5pdhnr+Wr1Mg6/kZSQHJWQYjR4qLs5uy5A6XwWUZtVYvDMt2RcbO8Yz8ZRLy/JGds7LpTocrn8CL9a5SxQeDaPYREzTKF+400U4pFMY50V1QenJrnO43n//pDY9Z8vNI+pe6YX3TpmQ/iyr9dZi1KyuViyDZRX2goNHAOWTubEXNDYd/LAsekQaN/7Q7+MdRnfFy+U0pposcqn3ZWEJSZV4OLz24j1eUdQYqw21M2m/FOgdsdNDrcJEKUM4yOjhuxBlrymm11+LsT68KgeLwdMLMdvrSS1TaaU8YfHbuhaJwxyxcOPkIbwNZNRmvlL2l/Mp0TqM4gLVX3ZoSEAzZlZN91o7u4aHLpcQtMICfNaxbr9HaHNf0rlvZo7UlkBvbDmbs3hgAseJSTbwM0mdh83laMneFkAbJiuOSU8OBSG6GblD+Aa0Mu04pXTFvg0jdelDSCHEbWthcc1srqoZf0Nt3kS6k9DHVjZ8J+Xeybgp+oSTKSlHPZkjkxfOnl6/x0H/D5goEGYRRWnTcx8rDITUf6iLRgtyMld6YpwRGeG7ru/DdzmvQd+UowMtzA1xnLq4qSWObzso=
