on:
  push:
    branches:
      - main
      - master
    
name: build 

jobs:
  render:
    name: build
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: 'https://tbep-tech.r-universe.dev'
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install macOS dependencies for tbeptools
        run: |
          rm -rf /usr/local/bin/gfortran
          brew install cairo
          brew install gdal
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::here
            any::tidyr
            any::lubridate
            any::stringr
            any::readxl
            any::testthat
            tbeptools
      - name: Update data
        run: Rscript -e 'source("R/dat_proc.R")'
      - name: Run tests
        run: Rscript -e "library(testthat); testthat::test_dir('tests/testthat', reporter = c('progress', 'fail'))"
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m 'Re-build data and run tests' || echo "No changes to commit"
          git push origin || echo "No changes to commit"